In [1]:
import torch
from torch.functional import F

In [2]:
tensor = torch.randint(-100, 100, (96, 1)).view(6, 4, 4)/ 100
tensor

tensor([[[-0.8600,  0.3800,  0.6800, -0.6500],
         [ 0.1700, -0.5100,  0.1000, -0.9800],
         [ 0.6100, -0.3800, -0.1900,  0.0600],
         [ 0.7100,  0.2200, -0.9700,  0.0500]],

        [[ 0.2500, -0.5200, -0.9000, -0.9600],
         [ 0.0600, -0.4600,  0.0700,  0.3300],
         [ 0.4200, -0.9700,  0.6800,  0.4500],
         [-0.5800,  0.4900,  0.5200, -0.5700]],

        [[ 0.8700, -0.5300, -0.7700, -0.9100],
         [-0.6000, -0.5600,  0.0400,  0.0600],
         [-0.4400,  0.4000, -0.2300,  0.1600],
         [ 0.0700, -0.3600,  0.0300, -0.7300]],

        [[ 0.1100, -0.5100, -0.1600,  0.3200],
         [-0.2300, -0.0100,  0.5200,  0.2600],
         [-0.9800, -0.2600,  0.6200,  0.0000],
         [ 0.7400, -0.5200, -0.5900, -0.9900]],

        [[-0.4800, -0.7400, -0.8200,  0.6500],
         [ 0.6300,  0.6900, -0.2000,  0.1300],
         [-0.5100,  0.3400,  0.6900,  0.4200],
         [-0.3700,  0.2600,  0.8600,  0.1500]],

        [[-0.2700,  0.4200,  0.4900, -0.1400],
   

In [66]:
tensor = tensor.view(2, 12, 4).float()
tensor

tensor([[[-0.7400, -0.9600, -0.7000, -0.5100],
         [ 0.4100,  0.8100,  0.0400, -0.3000],
         [-0.9400, -0.5700, -0.7100, -0.7400],
         [ 0.1400,  0.0800,  0.8100,  0.1100],
         [-0.1700,  0.8900, -0.8100, -0.6400],
         [ 0.7400, -0.8500,  0.7500, -0.6800],
         [ 0.6300,  0.7600,  0.1800, -0.0500],
         [-0.0600, -0.5300,  0.4300,  0.0900],
         [ 0.1200,  0.3700,  0.8500,  0.7700],
         [ 0.9700, -0.7100, -0.8600,  0.5600],
         [-0.8600,  0.4100, -0.1900,  0.2100],
         [ 0.8400, -0.3900, -0.5300, -0.9800]],

        [[-0.5900, -0.2000, -0.5900, -0.6100],
         [-0.8200,  0.0000, -0.4700, -0.0700],
         [ 0.4400, -0.8200,  0.3000,  0.5300],
         [-0.8300, -0.9900, -0.0900, -0.3900],
         [ 0.0500,  0.2600,  0.4100,  0.7100],
         [-0.7700,  0.8600,  0.5600, -0.1300],
         [-0.4100, -0.9900, -0.0300,  0.1800],
         [-0.5600,  0.2300,  0.1000, -0.9500],
         [-0.5600,  0.7400,  0.6300,  0.2300],
         [ 

In [67]:
out = F.softmax(tensor, dim=0)
out

tensor([[[0.4626, 0.3186, 0.4725, 0.5250],
         [0.7738, 0.6921, 0.6248, 0.4428],
         [0.2010, 0.5622, 0.2670, 0.2193],
         [0.7251, 0.7446, 0.7109, 0.6225],
         [0.4452, 0.6525, 0.2279, 0.2059],
         [0.8191, 0.1532, 0.5474, 0.3659],
         [0.7388, 0.8520, 0.5523, 0.4428],
         [0.6225, 0.3186, 0.5818, 0.7388],
         [0.6637, 0.4085, 0.5548, 0.6318],
         [0.5349, 0.5597, 0.4900, 0.7068],
         [0.2932, 0.5399, 0.2387, 0.6502],
         [0.7807, 0.2423, 0.4207, 0.4452]],

        [[0.5374, 0.6814, 0.5275, 0.4750],
         [0.2262, 0.3079, 0.3752, 0.5572],
         [0.7990, 0.4378, 0.7330, 0.7807],
         [0.2749, 0.2554, 0.2891, 0.3775],
         [0.5548, 0.3475, 0.7721, 0.7941],
         [0.1809, 0.8468, 0.4526, 0.6341],
         [0.2612, 0.1480, 0.4477, 0.5572],
         [0.3775, 0.6814, 0.4182, 0.2612],
         [0.3363, 0.5915, 0.4452, 0.3682],
         [0.4651, 0.4403, 0.5100, 0.2932],
         [0.7068, 0.4601, 0.7613, 0.3498],
         

In [68]:
out.view(6, 4, 4)

tensor([[[0.4626, 0.3186, 0.4725, 0.5250],
         [0.7738, 0.6921, 0.6248, 0.4428],
         [0.2010, 0.5622, 0.2670, 0.2193],
         [0.7251, 0.7446, 0.7109, 0.6225]],

        [[0.4452, 0.6525, 0.2279, 0.2059],
         [0.8191, 0.1532, 0.5474, 0.3659],
         [0.7388, 0.8520, 0.5523, 0.4428],
         [0.6225, 0.3186, 0.5818, 0.7388]],

        [[0.6637, 0.4085, 0.5548, 0.6318],
         [0.5349, 0.5597, 0.4900, 0.7068],
         [0.2932, 0.5399, 0.2387, 0.6502],
         [0.7807, 0.2423, 0.4207, 0.4452]],

        [[0.5374, 0.6814, 0.5275, 0.4750],
         [0.2262, 0.3079, 0.3752, 0.5572],
         [0.7990, 0.4378, 0.7330, 0.7807],
         [0.2749, 0.2554, 0.2891, 0.3775]],

        [[0.5548, 0.3475, 0.7721, 0.7941],
         [0.1809, 0.8468, 0.4526, 0.6341],
         [0.2612, 0.1480, 0.4477, 0.5572],
         [0.3775, 0.6814, 0.4182, 0.2612]],

        [[0.3363, 0.5915, 0.4452, 0.3682],
         [0.4651, 0.4403, 0.5100, 0.2932],
         [0.7068, 0.4601, 0.7613, 0.3498],
 

In [69]:
oout = out.view(6, 4, 4).permute(1, 2, 0)
oout

tensor([[[0.4626, 0.4452, 0.6637, 0.5374, 0.5548, 0.3363],
         [0.3186, 0.6525, 0.4085, 0.6814, 0.3475, 0.5915],
         [0.4725, 0.2279, 0.5548, 0.5275, 0.7721, 0.4452],
         [0.5250, 0.2059, 0.6318, 0.4750, 0.7941, 0.3682]],

        [[0.7738, 0.8191, 0.5349, 0.2262, 0.1809, 0.4651],
         [0.6921, 0.1532, 0.5597, 0.3079, 0.8468, 0.4403],
         [0.6248, 0.5474, 0.4900, 0.3752, 0.4526, 0.5100],
         [0.4428, 0.3659, 0.7068, 0.5572, 0.6341, 0.2932]],

        [[0.2010, 0.7388, 0.2932, 0.7990, 0.2612, 0.7068],
         [0.5622, 0.8520, 0.5399, 0.4378, 0.1480, 0.4601],
         [0.2670, 0.5523, 0.2387, 0.7330, 0.4477, 0.7613],
         [0.2193, 0.4428, 0.6502, 0.7807, 0.5572, 0.3498]],

        [[0.7251, 0.6225, 0.7807, 0.2749, 0.3775, 0.2193],
         [0.7446, 0.3186, 0.2423, 0.2554, 0.6814, 0.7577],
         [0.7109, 0.5818, 0.4207, 0.2891, 0.4182, 0.5793],
         [0.6225, 0.7388, 0.4452, 0.3775, 0.2612, 0.5548]]])

In [77]:
oout.shape, oout[:,:,0].shape

(torch.Size([4, 4, 6]), torch.Size([4, 4]))

In [78]:
oout[:,:,0]

tensor([[0.4626, 0.3186, 0.4725, 0.5250],
        [0.7738, 0.6921, 0.6248, 0.4428],
        [0.2010, 0.5622, 0.2670, 0.2193],
        [0.7251, 0.7446, 0.7109, 0.6225]])

In [83]:
tensor1 = torch.randn(3, 2, 4)
out1 = F.softmax(tensor1, dim=1)
out1

tensor([[[0.8622, 0.8400, 0.4913, 0.3642],
         [0.1378, 0.1600, 0.5087, 0.6358]],

        [[0.1939, 0.4151, 0.7576, 0.2205],
         [0.8061, 0.5849, 0.2424, 0.7795]],

        [[0.5693, 0.1876, 0.7592, 0.4370],
         [0.4307, 0.8124, 0.2408, 0.5630]]])

In [84]:
out1[1].sum(), out[1].sum()

(tensor(4.), tensor(23.2094))

In [89]:
out1.view(1,-1)

tensor([[0.8622, 0.8400, 0.4913, 0.3642, 0.1378, 0.1600, 0.5087, 0.6358, 0.1939,
         0.4151, 0.7576, 0.2205, 0.8061, 0.5849, 0.2424, 0.7795, 0.5693, 0.1876,
         0.7592, 0.4370, 0.4307, 0.8124, 0.2408, 0.5630]])

In [92]:
out1.shape, out1, out1[:, 0].shape, out1[:, 0].reshape(1,-1).shape

(torch.Size([3, 2, 4]),
 tensor([[[0.8622, 0.8400, 0.4913, 0.3642],
          [0.1378, 0.1600, 0.5087, 0.6358]],
 
         [[0.1939, 0.4151, 0.7576, 0.2205],
          [0.8061, 0.5849, 0.2424, 0.7795]],
 
         [[0.5693, 0.1876, 0.7592, 0.4370],
          [0.4307, 0.8124, 0.2408, 0.5630]]]),
 torch.Size([3, 4]),
 torch.Size([1, 12]))

In [5]:
feat_height, feat_width = 3, 4
shift_x = torch.arange(0, feat_width) * 5
shift_y = torch.arange(0, feat_height) * 5
shift_x, shift_y

(tensor([ 0,  5, 10, 15]), tensor([ 0,  5, 10]))

In [6]:
shift_x1, shift_y1 = torch.meshgrid(shift_x, shift_y, indexing='xy')
shift_x1, shift_y1, shift_y1.shape

(tensor([[ 0,  5, 10, 15],
         [ 0,  5, 10, 15],
         [ 0,  5, 10, 15]]),
 tensor([[ 0,  0,  0,  0],
         [ 5,  5,  5,  5],
         [10, 10, 10, 10]]),
 torch.Size([3, 4]))

In [7]:
shift_x1.flatten()

tensor([ 0,  5, 10, 15,  0,  5, 10, 15,  0,  5, 10, 15])

In [8]:
shift_x1, shift_y1 = torch.meshgrid(shift_x, shift_y, indexing='ij')
shift_x1, shift_y1, shift_y1.shape

(tensor([[ 0,  0,  0],
         [ 5,  5,  5],
         [10, 10, 10],
         [15, 15, 15]]),
 tensor([[ 0,  5, 10],
         [ 0,  5, 10],
         [ 0,  5, 10],
         [ 0,  5, 10]]),
 torch.Size([4, 3]))

In [9]:
[shift_x1.flatten()] * 4

[tensor([ 0,  0,  0,  5,  5,  5, 10, 10, 10, 15, 15, 15]),
 tensor([ 0,  0,  0,  5,  5,  5, 10, 10, 10, 15, 15, 15]),
 tensor([ 0,  0,  0,  5,  5,  5, 10, 10, 10, 15, 15, 15]),
 tensor([ 0,  0,  0,  5,  5,  5, 10, 10, 10, 15, 15, 15])]

In [10]:
feat_height, feat_width = 3, 4
# feature stride !in origin image!
shift_x, shift_y = torch.arange(0, feat_width) * 6,\
    torch.arange(0, feat_height) * 6
# meshrgid: from [1, N] and [1, K] -> [K, N] if "xy" or [N, K] if "ij" like:
shift_x, shift_y = torch.meshgrid(shift_x, shift_y, indexing='xy')
print(shift_x,'\n', shift_y)
# flatten: from [N, K] to [1, N*K]
shifts = torch.vstack([
    shift_x.flatten(), shift_y.flatten(),
    shift_x.flatten(), shift_y.flatten()])
shifts, shifts.T

tensor([[ 0,  6, 12, 18],
        [ 0,  6, 12, 18],
        [ 0,  6, 12, 18]]) 
 tensor([[ 0,  0,  0,  0],
        [ 6,  6,  6,  6],
        [12, 12, 12, 12]])


(tensor([[ 0,  6, 12, 18,  0,  6, 12, 18,  0,  6, 12, 18],
         [ 0,  0,  0,  0,  6,  6,  6,  6, 12, 12, 12, 12],
         [ 0,  6, 12, 18,  0,  6, 12, 18,  0,  6, 12, 18],
         [ 0,  0,  0,  0,  6,  6,  6,  6, 12, 12, 12, 12]]),
 tensor([[ 0,  0,  0,  0],
         [ 6,  0,  6,  0],
         [12,  0, 12,  0],
         [18,  0, 18,  0],
         [ 0,  6,  0,  6],
         [ 6,  6,  6,  6],
         [12,  6, 12,  6],
         [18,  6, 18,  6],
         [ 0, 12,  0, 12],
         [ 6, 12,  6, 12],
         [12, 12, 12, 12],
         [18, 12, 18, 12]]))

In [21]:
shifts = shifts.T

In [23]:
shifts.view(-1, 1 , 4)

tensor([[[ 0,  0,  0,  0]],

        [[ 6,  0,  6,  0]],

        [[12,  0, 12,  0]],

        [[18,  0, 18,  0]],

        [[ 0,  6,  0,  6]],

        [[ 6,  6,  6,  6]],

        [[12,  6, 12,  6]],

        [[18,  6, 18,  6]],

        [[ 0, 12,  0, 12]],

        [[ 6, 12,  6, 12]],

        [[12, 12, 12, 12]],

        [[18, 12, 18, 12]]])

In [15]:
K = torch.arange(0, 6).view(1, 3, 2)
A = torch.arange(0, 8).view(4, 1, 2)
K, A

(tensor([[[0, 1],
          [2, 3],
          [4, 5]]]),
 tensor([[[0, 1]],
 
         [[2, 3]],
 
         [[4, 5]],
 
         [[6, 7]]]))

In [16]:
(K + A), (K + A).size()

(tensor([[[ 0,  2],
          [ 2,  4],
          [ 4,  6]],
 
         [[ 2,  4],
          [ 4,  6],
          [ 6,  8]],
 
         [[ 4,  6],
          [ 6,  8],
          [ 8, 10]],
 
         [[ 6,  8],
          [ 8, 10],
          [10, 12]]]),
 torch.Size([4, 3, 2]))

In [20]:
K + A[0]

tensor([[[0, 2],
         [2, 4],
         [4, 6]]])

In [13]:
from faster.rpn import bbox_transform_inv 

In [14]:
batch_size, feat_h, feat_w, num_Anchors = 4, 20, 30, 9
anchors = torch.randn([batch_size, feat_h*feat_w*num_Anchors, 4])
delta_bboxes = torch.randn([batch_size, feat_h*feat_w*9, 4])
res = bbox_transform_inv(anchors, delta_bboxes, batch_size)

In [15]:
res.shape

torch.Size([4, 5400, 4])

In [21]:
K, A = torch.arange(0, 36).view(1, 9, 4), torch.torch.arange(0, 40).view(10, 1, 4)
K, K.shape, A, A.shape 

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35]]]),
 torch.Size([1, 9, 4]),
 tensor([[[ 0,  1,  2,  3]],
 
         [[ 4,  5,  6,  7]],
 
         [[ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15]],
 
         [[16, 17, 18, 19]],
 
         [[20, 21, 22, 23]],
 
         [[24, 25, 26, 27]],
 
         [[28, 29, 30, 31]],
 
         [[32, 33, 34, 35]],
 
         [[36, 37, 38, 39]]]),
 torch.Size([10, 1, 4]))

In [22]:
K + A, (K + A).shape

(tensor([[[ 0,  2,  4,  6],
          [ 4,  6,  8, 10],
          [ 8, 10, 12, 14],
          [12, 14, 16, 18],
          [16, 18, 20, 22],
          [20, 22, 24, 26],
          [24, 26, 28, 30],
          [28, 30, 32, 34],
          [32, 34, 36, 38]],
 
         [[ 4,  6,  8, 10],
          [ 8, 10, 12, 14],
          [12, 14, 16, 18],
          [16, 18, 20, 22],
          [20, 22, 24, 26],
          [24, 26, 28, 30],
          [28, 30, 32, 34],
          [32, 34, 36, 38],
          [36, 38, 40, 42]],
 
         [[ 8, 10, 12, 14],
          [12, 14, 16, 18],
          [16, 18, 20, 22],
          [20, 22, 24, 26],
          [24, 26, 28, 30],
          [28, 30, 32, 34],
          [32, 34, 36, 38],
          [36, 38, 40, 42],
          [40, 42, 44, 46]],
 
         [[12, 14, 16, 18],
          [16, 18, 20, 22],
          [20, 22, 24, 26],
          [24, 26, 28, 30],
          [28, 30, 32, 34],
          [32, 34, 36, 38],
          [36, 38, 40, 42],
          [40, 42, 44, 46],
          [

In [24]:
# tensor = torch.arange(0, 24).view(3, 2, 4) + 5
tensor = torch.randint().view(3, 2, 4) + 5
tensor

tensor([[[ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20]],

        [[21, 22, 23, 24],
         [25, 26, 27, 28]]])

In [25]:
tensor.argmax(dim=1)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [ ]:
# keep original order?
# save 3 max area values? 
# берем каждый из свобождных, argmax вычитаем из overlaps
# постепенно поднимать отсечение - ибо может сойтись к такому margin
# допустим NMS - это хорошо, 
# что если усреднять ближайшие слои якорей свёркти
# между собой и тем самым уменьшать кол-во якорей на инференсе - условно адаптивный якорь 
# получаем.сначала маленький батч сайз, но много якорей, 
# а затем большой батч и мало якорей
# проверка, все ли gt boxes попали в output после NMS

In [ ]:
for gt in 